Task_1_2_2
melarozz/OOP pull request #10
Opened 2023-10-30 18:35 UTC by melarozz

2023-11-04 13:16 UTC, shadrina requested changes

2023-11-04 13:16 UTC, shadrina commented on Task_1_2_2/src/main/java/ru/nsu/yakovleva/graph/Graph.java
> +        return 0;
Перепиши пожалуйста с `return switch ...`. Switch expression как раз для такого и нужен

2023-11-04 13:16 UTC, shadrina commented on Task_1_2_2/src/main/java/ru/nsu/yakovleva/graph/Graph.java
> +        return 0;
Вообще можно заметить, что все методы ниже устроены одинаково, и у них та же проблема, которая была с алгоритмом -- они напрямую завязаны на тип матрицы. Буквально каждый метод это похожий if else. Почему это плохо, я говорила:
- Повторяющийся код всегда error-prone
- Появится новый тип матрицы -- переписывать надо вообще все.

Явно напрашивается один общий интерфейс Graph и три имплементации. И не будет никаких if, потому что каждая имплементация точно знает, какой тип описывает. И если появится новая имплементация, не потребуется значительно менять существующий код.

Я этот файл на паре видела в таком состоянии?

2023-11-04 13:16 UTC, shadrina commented on Task_1_2_2/src/main/java/ru/nsu/yakovleva/graph/algorithms/Dijkstra.java
> +        if (matrixType == Graph.MatrixType.INC_MATR) {
И соответственно вот это проверка заменится на проверку `instanceof`.

2023-11-04 13:16 UTC, shadrina commented on Task_1_2_2/src/test/java/ru/nsu/yakovleva/graph/GraphTest.java
> +                    classLoader.getResource("adjacency_matrix_input.txt")).getPath();
Можно и так, ок. Обычно более компактно получается с getResourceAsStream(), тогда он сразу открывается в стрим.

2023-11-06 09:35 UTC, melarozz commented on Task_1_2_2/src/main/java/ru/nsu/yakovleva/graph/Graph.java
> +        return 0;
Да, видели, и на мягком,  и на жестком. Про граф замечаний не было, только на алгоритм.  Обязательно интерфейсом делать? Если я просто буду представления в матрицу смежности переделывать при инициализации и работать с ними, это не будет ок?

2023-11-20 16:29 UTC, shadrina approved these changes

2023-11-20 17:07 UTC, merged