Task_1_5_1
melarozz/OOP pull request #13
Opened 2023-12-04 15:09 UTC by melarozz

2023-12-12 09:07 UTC, shadrina requested changes

2023-12-12 09:07 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/yakovleva/calculator/Main.java
> +public class Main {
Это не `Main`, это `Calculator`. Либо нужно отдельно `Main` с main-методом и отдельно `Calculator`

2023-12-12 09:07 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/yakovleva/calculator/Main.java
> +    private static Flag flag = Flag.NORMAL;
Конкретно в этом случае было бы более удобно завести просто boolean флаг `degreesMode`. Тогда ушли бы лишние `==`

2023-12-12 09:07 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/yakovleva/calculator/Main.java
> +        }
Ну хотя бы switch по строкам. По-хорошему я, конечно, хотела бы свой класс/перечисление операций

2023-12-12 09:07 UTC, shadrina commented on Task_1_5_1/src/test/java/ru/nsu/yakovleva/calculator/CalcTest.java
> +    void testLettersException() {
- Нет тестов с нецелочисленными значениями
- Нет большого теста с использованием всех операций

2023-12-12 12:22 UTC, melarozz commented
Мне очень хотелось сделать поддержку комплексных чисел)
Если есть что сделать красивее - я готова делать правки
Но в целом я попыталась сделать какую-то архитектуру

2023-12-18 10:05 UTC, shadrina requested changes

2023-12-18 10:05 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/yakovleva/calculator/Complex.java
> +        }
Существует switch expression, а не switch statement (который тут используется).

Switch expression является выражением и имеет возвращаемое значение:
```
return switch (operator) {
    case "+" -> operand1.add(operand2);
    case "-" -> ...
    ...
}
```

2023-12-18 10:05 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/yakovleva/calculator/Complex.java
> +    }
Аналогично

2023-12-18 10:05 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/yakovleva/calculator/NormalAndDegrees.java
> +    }
Аналогично

2023-12-18 10:05 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/yakovleva/calculator/NormalAndDegrees.java
> +                    || ("sin".equals(token)) || ("cos".equals(token)) || ("log".equals(token));
1) Вынести isOperator в отдельный статический метод. Это точно единственное место, где такая функциональность используется? Мне кажется, оно может и в других местах пригодиться.
2) Проверь сначала что это либо нумерик, либо оператор. Если ни то, ни другое, сразу кидай исключение. Таким образом, можно будет всю дальнейшую логику разместить без дополнительной вложенности, которая мешает читать код.

2023-12-18 10:05 UTC, shadrina commented on Task_1_5_1/src/main/java/ru/nsu/yakovleva/calculator/NormalAndDegrees.java
> +    }
Аналогично

2023-12-18 10:50 UTC, melarozz commented on Task_1_5_1/src/main/java/ru/nsu/yakovleva/calculator/Complex.java
> +        }
градл не дает так делать, билд падает :(

2023-12-18 11:13 UTC, melarozz commented on Task_1_5_1/src/main/java/ru/nsu/yakovleva/calculator/Complex.java
> +        }
починила)

2023-12-19 04:13 UTC, shadrina approved these changes

2023-12-19 04:26 UTC, merged