Task_1_2_1
melarozz/OOP pull request #9
Opened 2023-10-24 04:26 UTC by melarozz

2023-10-28 10:23 UTC, shadrina requested changes

2023-10-28 10:23 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/yakovleva/tree/Tree.java
> +        return node.equals(otherTree.getNodeName());
Тут скорее всего просто ничего не поменялось с прошлой пары. А запрос ревью стоит

2023-10-28 11:14 UTC, melarozz commented on Task_1_2_1/src/main/java/ru/nsu/yakovleva/tree/Tree.java
> +        return node.equals(otherTree.getNodeName());
Здравствуйте, а что менять? У меня было исправлено сравнение хеш-кода еще на той неделе, Вы мне это и объясняли первой :(

2023-10-28 11:22 UTC, shadrina requested changes

2023-10-28 11:22 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/yakovleva/tree/Tree.java
> +        return node.equals(otherTree.getNodeName());
Я еще в начале пары сказала всем проверить реализацию equals. Что она проверяет равенство всего поддерева. Здесь же проверяется только родитель и значение верхней ноды.

2023-10-28 11:22 UTC, shadrina commented on Task_1_2_1/src/test/java/ru/nsu/yakovleva/tree/TreeTest.java
> +        assertNotSame(tree1, tree2);
Вот это работает, потому что `assertSame()` проверяет не равенство по equals, а refencial equality, то есть `==`. Для аналогичной проверки по equals есть метод `assertNotEquals()`.

2023-10-28 11:24 UTC, shadrina commented on Task_1_2_1/src/test/java/ru/nsu/yakovleva/tree/TreeTest.java
> +        assertNotSame(tree1, tree2);
Я надеюсь, что разница понятна

2023-10-28 11:24 UTC, melarozz commented on Task_1_2_1/src/main/java/ru/nsu/yakovleva/tree/Tree.java
> +        return node.equals(otherTree.getNodeName());
Поняла, про сравнение родителей.

2023-10-28 11:29 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/yakovleva/tree/Tree.java
> +        return node.equals(otherTree.getNodeName());
Проблема не в сравнении родителей, а в отсутствии сравнения детей) То есть метод далее по дереву рекурсивно ничего не проверяет.

2023-10-28 11:29 UTC, shadrina commented on Task_1_2_1/src/test/java/ru/nsu/yakovleva/tree/TreeTest.java
> +        assertNotSame(tree1, tree2);
И если здесь поставить правильный assertNotEquals, тест упадет

2023-11-04 11:13 UTC, shadrina approved these changes

2023-11-04 11:13 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/yakovleva/tree/Tree.java
> +        }
Вот ровно это скорее всего делает Arrays.equals

2023-11-04 13:36 UTC, merged